export const movies = [
  {
    id:0,
    Title: "John Wick: Chapter 4",
    Year: "2023",
    Rated: "N/A",
    Released: "24 Mar 2023",
    Runtime: "169 min",
    Genre: "Action, Crime, Thriller",
    Director: "Chad Stahelski",
    Writer: "Shay Hatten, Michael Finch, Derek Kolstad",
    Actors: "Keanu Reeves, Donnie Yen, Bill Skarsgård",
    Plot: "John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMDExZGMyOTMtMDgyYi00NGIwLWJhMTEtOTdkZGFjNmZiMTEwXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_SX300.jpg",
    Ratings: [],
    Metascore: "N/A",
    imdbRating: "N/A",
    imdbVotes: "N/A",
    imdbID: "tt10366206",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "Lionsgate",
    Website: "N/A",
    Response: "True",
    Sale:[3,5,7,10,11],
    Disponibile: "12 Maggio"
  },
  {
    id:1,
    Title: "Shazam! Fury of the Gods",
    Year: "2023",
    Rated: "PG-13",
    Released: "17 Mar 2023",
    Runtime: "130 min",
    Genre: "Action, Adventure, Comedy",
    Director: "David F. Sandberg",
    Writer: "Henry Gayden, Chris Morgan, Bill Parker",
    Actors: "Zachary Levi, Asher Angel, Jack Dylan Grazer",
    Plot: 'The film continues the story of teenage Billy Batson who, upon reciting the magic word "SHAZAM!" is transformed into his adult Super Hero alter ego, Shazam.',
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNzJlM2NmZTItOGQyYS00MmE2LTkwZGUtNDFkNmJmZjRjZjcxXkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "6.7/10" },
      { Source: "Metacritic", Value: "46/100" },
    ],
    Metascore: "46",
    imdbRating: "6.7",
    imdbVotes: "6,304",
    imdbID: "tt10151854",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "Warner Bros. Pictures",
    Website: "N/A",
    Response: "True",
    Sale:[1,5,7,8],
    Disponibile: "1 Maggio"
  },
  {
    id:2,
    Title: "The Whale",
    Year: "2022",
    Rated: "R",
    Released: "21 Dec 2022",
    Runtime: "117 min",
    Genre: "Drama",
    Director: "Darren Aronofsky",
    Writer: "Samuel D. Hunter",
    Actors: "Brendan Fraser, Sadie Sink, Ty Simpkins",
    Plot: "A reclusive, morbidly obese English teacher attempts to reconnect with his estranged teenage daughter.",
    Language: "English",
    Country: "United States",
    Awards: "Nominated for 3 Oscars. 40 wins & 114 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZDQ4Njg4YTctNGZkYi00NWU1LWI4OTYtNmNjOWMyMjI1NWYzXkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.8/10" },
      { Source: "Rotten Tomatoes", Value: "65%" },
      { Source: "Metacritic", Value: "60/100" },
    ],
    Metascore: "60",
    imdbRating: "7.8",
    imdbVotes: "80,564",
    imdbID: "tt13833688",
    Type: "movie",
    DVD: "21 Feb 2023",
    BoxOffice: "$16,966,332",
    Production: "A24",
    Website: "N/A",
    Response: "True",
    Sale:[9,11,12],
    Disponibile: "17 Aprile"
  },
  {
    id: 3,
    Title: "Creed III",
    Year: "2023",
    Rated: "PG-13",
    Released: "03 Mar 2023",
    Runtime: "116 min",
    Genre: "Drama, Sport",
    Director: "Michael B. Jordan",
    Writer: "Keenan Coogler, Zach Baylin, Ryan Coogler",
    Actors: "Michael B. Jordan, Tessa Thompson, Jonathan Majors",
    Plot: "Adonis has been thriving in both his career and family life, but when a childhood friend and former boxing prodigy resurfaces, the face-off is more than just a fight.",
    Language: "English, Spanish, American Sign ",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYWY1ZDY4MmQtYjhiYS00N2QwLTk1NzgtOWI2YzUwZThjNDYwXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.3/10" },
      { Source: "Rotten Tomatoes", Value: "89%" },
      { Source: "Metacritic", Value: "73/100" },
    ],
    Metascore: "73",
    imdbRating: "7.3",
    imdbVotes: "27,651",
    imdbID: "tt11145118",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$130,444,403",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
    Sale:[7,8,11],
    Disponibile: "25 Giugno"
  },
  {
    id: 4,
    Title: "Scream VI",
    Year: "2023",
    Rated: "R",
    Released: "10 Mar 2023",
    Runtime: "123 min",
    Genre: "Horror, Mystery, Thriller",
    Director: "Matt Bettinelli-Olpin, Tyler Gillett",
    Writer: "James Vanderbilt, Guy Busick, Kevin Williamson",
    Actors: "Melissa Barrera, Courteney Cox, Jenna Ortega",
    Plot: "In the next installment, the survivors of the Ghostface killings leave Woodsboro behind and start a fresh chapter in New York City.",
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYTQ5OTkxNGEtZjZkMS00ZjBlLWE2OWYtM2ZkOTU3MjRlNzAxXkEyXkFqcGdeQXVyMTQzNTA5MzYz._V1_SX300.jpg",
    Ratings: [{ Source: "Rotten Tomatoes", Value: "76%" }],
    Metascore: "N/A",
    imdbRating: "N/A",
    imdbVotes: "N/A",
    imdbID: "tt17663992",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "Paramount Pictures",
    Website: "N/A",
    Response: "True",
    Sale:[3,5,7],
    Disponibile: "12 Aprile"
  },
  {
    id: 5,
    Title: "Ant-Man and the Wasp",
    Year: "2018",
    Rated: "PG-13",
    Released: "06 Jul 2018",
    Runtime: "118 min",
    Genre: "Action, Adventure, Comedy",
    Director: "Peyton Reed",
    Writer: "Chris McKenna, Erik Sommers, Paul Rudd",
    Actors: "Paul Rudd, Evangeline Lilly, Michael Peña",
    Plot: "As Scott Lang balances being both a superhero and a father, Hope van Dyne and Dr. Hank Pym present an urgent new mission that finds the Ant-Man fighting alongside The Wasp to uncover secrets from their past.",
    Language: "English, Spanish, French",
    Country: "United States, Canada",
    Awards: "2 wins & 21 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYjcyYTk0N2YtMzc4ZC00Y2E0LWFkNDgtNjE1MzZmMGE1YjY1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.0/10" },
      { Source: "Rotten Tomatoes", Value: "87%" },
      { Source: "Metacritic", Value: "70/100" },
    ],
    Metascore: "70",
    imdbRating: "7.0",
    imdbVotes: "415,093",
    imdbID: "tt5095030",
    Type: "movie",
    DVD: "08 Dec 2015",
    BoxOffice: "$216,648,740",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
    Sale:[1,2,10],
    Disponibile: "30 Aprile"
  },
];
